### PR TITLE
Saloon Interactable Updates

### PR DESCRIPTION
**Pull request by ntelfer**

### CODE REVIEW

**Comment by michaelmendoza** [comment]
Sweet! Thanks!

**Comment by michaelmendoza** [comment]
Oh, just a note for the future. @ntelfer  I would do a pull request into dev instead of master. I just noticed.

**Comment by ntelfer** [comment]
Oh woops!  Sorry! It defaults to master and I forgot to change it to dev.

**Comment by michaelmendoza** [comment]
No worries! Master was to date with dev so it didn't cause any issues

**Pull request merged**
